### ISSUE TITLE
[Regression in 2.0.0] [Arch Linux, KDE Plasma 5.4.0] Cannot bring up context menu from tray icon

### ISSUE THREAD

**Issue by protist** [owncloud/client#3706]
### Expected behaviour
Right click on tray icon to bring up context menu.

### Actual behaviour
Nothing.

### Steps to reproduce
1. Right-click tray icon.

### Server configuration
Operating system: Raspbian

Web server: Apache

Database: mysql

PHP version: 5.6.12

ownCloud version: 8.1.1

Storage backend: ??

### Client configuration
Client version: 2.0.0, bug not seen in previous install of 1.8.4.

Operating system: Arch Linux, running KDE Plasma 5.4.0

OS language: English

Installation path of client: `/usr/bin/owncloud`

### Logs

Output of `owncloud --logwindow` is [here](https://gist.github.com/protist/e0499d05de047358feca).

### Additional information
When booting the computer, I am presented with a password input field to unlock my keychain. Below this is the Owncloud client configuration window. However, there seems to be no clear way to open this configuration window after this. Is there some other way to open this?

Finally, I can rollover the tray icon, and the popup appears to work correctly.

**Comment by guruz** [comment]
> Finally, I can rollover the tray icon, and the popup appears to work correctly.

What does that mean?

FYI @ogoffart

**Comment by protist** [comment]
I meant that when I hover over the icon, I see the popup as below.
![Screenshot](http://i.imgur.com/ZpzXsHj.png)
I wanted to imply that the icon hadn't totally frozen.

**Comment by ogoffart** [comment]
What's the version of Qt?

**Comment by protist** [comment]
qt4: 4.8.7
qt5: 5.5.0

**Comment by guruz** [comment]
@protist But which one is acutually used?
You can run the client with:
```owncloud --logfile -```
and search for "Qt"

**Comment by protist** [comment]
Ah I see. It's in the log linked in the first post: `Qt 5.5.0`.

**Comment by drguell** [comment]
I reproduce the same issue.

$ owncloud --logfile - | grep -i qt
08-31 13:27:14:645 23720 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
08-31 13:27:17:508 23720 OCC::SyncEngine::startSync: =====Using Qt 5.5.0
08-31 13:27:17:731 23720 OCC::Folder::slotSyncFinished:  - client version 2.0.0  Qt 5.5.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
08-31 13:27:20:061 23720 OCC::SyncEngine::startSync: =====Using Qt 5.5.0

**Comment by ckamm** [comment]
Probably related to #3672 and #3656

**Comment by protist** [comment]
FWIW the context menu was fine in 1.8.4, which I had installed on 2015-07-16. I had upgraded from qt5 5.4.2 to 5.5.0 the previous day. This combination of owncloud-client 1.8.4 and qt5 5.5.0 had worked fine for me, and I only saw problems after upgrading to owncloud-client 2.2.0.

I read the linked issues and tried to test if it were a bug in Qt5, by downgrading it to 5.4.2. However, owncloud-client refused to start, with

    owncloud: symbol lookup error: /usr/lib/libQt5Qml.so.5: undefined symbol: _ZNK18QAbstractListModel7siblingEiiRK11QModelIndex

I wasn't sure if I had to *build* using this earlier version of qt5, so I attempted to build, but had the errors:
```
CMake Error at /usr/lib64/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake:99 (find_package):
  Could not find a configuration file for package "Qt5Widgets" that is
  compatible with requested version "5.5.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.4.2

Call Stack (most recent call first):
  cmake/modules/QtVersionAbstraction.cmake:22 (find_package)
  CMakeLists.txt:54 (include)


-- Configuring incomplete, errors occurred!
See also "/foo/src/build/CMakeFiles/CMakeOutput.log".
```

I'm not sure if this troubleshooting is useful to you, so please let me know if you'd like me to continue, and how I should do it.

**Comment by ckamm** [comment]
@protist Thanks for the extra information! It'd be really useful to know whether this problem already existed with Qt <5.5.0. Maybe try downgrading again, including all qt5 modules that have the 5.5.0 version?

**Comment by protist** [comment]
Is the important part to *build* with Qt <5.5.0? If so, could you please tell me how to proceed? I was building from th

**Comment by protist** [comment]
I downgraded everything to 5.4.2, i.e.
```
qt5-base qt5-declarative qt5-graphicaleffects qt5-imageformats qt5-location qt5-multimedia qt5-quickcontrols qt5-script qt5-sensors qt5-svg qt5-tools qt5-translations qt5-webchannel qt5-webkit qt5-x11extras qt5-xmlpatterns
```
However, the build still failed for me, with
```
[ 70%] Building CXX object src/gui/CMakeFiles/owncloud.dir/owncloud_automoc.cpp.o
[ 70%] Linking CXX executable ../../bin/owncloud
libupdater.a(updateinfo.cpp.o): In function `OCC::UpdateInfo::parseElement(QDomElement const&, bool*)':
updateinfo.cpp:(.text+0x232): undefined reference to `QDebug::putString(QChar const*, unsigned long)'
libupdater.a(updateinfo.cpp.o): In function `OCC::UpdateInfo::parseString(QString const&, bool*)':
updateinfo.cpp:(.text+0x1165): undefined reference to `QDebug::putString(QChar const*, unsigned long)'
libupdater.a(updateinfo.cpp.o): In function `OCC::UpdateInfo::parseFile(QString const&, bool*)':
updateinfo.cpp:(.text+0x16c1): undefined reference to `QDebug::putString(QChar const*, unsigned long)'
updateinfo.cpp:(.text+0x199f): undefined reference to `QDebug::putString(QChar const*, unsigned long)'
libupdater.a(updateinfo.cpp.o): In function `OCC::UpdateInfo::writeFile(QString const&)':
updateinfo.cpp:(.text+0x1e5b): undefined reference to `QDebug::putString(QChar const*, unsigned long)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QString::toLower_helper(QString const&)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QString::trimmed_helper(QString const&)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QByteArray::toUpper_helper(QByteArray&)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QByteArray::trimmed_helper(QByteArray const&)'
../libsync/libowncloudsync.so.2.0.0: undefined reference to `QDebug::putByteArray(char const*, unsigned long, QDebug::Latin1Content)'
collect2: error: ld returned 1 exit status
src/gui/CMakeFiles/owncloud.dir/build.make:1960: recipe for target 'bin/owncloud' failed
make[2]: *** [bin/owncloud] Error 1
CMakeFiles/Makefile2:339: recipe for target 'src/gui/CMakeFiles/owncloud.dir/all' failed
make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ckamm** [comment]
@protist Once you downgraded the libraries, running the existing owncloud binary should be fine.

**Comment by nqn76** [comment]
owncloud-client built with Qt 5.4 works fine using Qt 5.5. So it's *building* against Qt 5.5 that breaks this.

**Comment by protist** [comment]
Oh, apologies, I made a build error earlier. I half built it with different versions of Qt5. I have a couple of data points, at least.

1) Downgrade Qt5 packages to 5.4.2, and run owncloud-client (built with Qt 5.5.0). It refuses to start and I get the following error.

    static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs
    owncloud: symbol lookup error: owncloud: undefined symbol: _ZN6QDebug9putStringEPK5QCharm

2) Downgrade Qt5 packages to 5.4.2, and run owncloud client (built with Qt 5.4.2). It launches, immediately showing the config window. However, there is no icon in the tray at all. I get the following warning.

    static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs

3) Upgrade Qt5 packages to 5.5.0, but run owncloud client (built with Qt 5.4.2). It launches, with no config window (similar to Qt 5.5.0 for build and running). However, the context menu works!

(Also, I'm going to bed now, so I'll respond in the morning.)

**Comment by ckamm** [comment]
Thanks for checking @protist  and @nqn76!

Ok:
* Built Qt 5.4, Run Qt 5.5
* Built Qt 5.4.2, Run Qt 5.5.0

Fail:
* Built Qt 5.5, Run Qt 5.5 
* Build Qt 5.4.2, Run Qt 5.4.2

That last failure is confusing. Can you test commenting `#define WORKAROUND_QT_TRAY_DBUS` in owncloudgui.cpp (2.0 branch) and check whether that makes a difference for the Qt 5.5.0 build/run case?

**Comment by nqn76** [comment]
> That last failure is confusing. 

That one is likely due to the downgrade of Qt breaking Plasma (which was built against 5.5), I doubt it's related to this issue

> Can you test commenting #define WORKAROUND_QT_TRAY_DBUS in owncloudgui.cpp  (2.0 branch) and check whether that makes a difference for the Qt 5.5.0 build/run case?

This fixes the context menu

**Comment by protist** [comment]
> That one is likely due to the downgrade of Qt breaking Plasma (which was built against 5.5), I doubt it's related to this issue

Yes, I agree with @nqn76. For example, after downgrading Qt, I can no longer extract archives with KDE's `ark`. I get a similar error to owncloud-client

    ark: symbol lookup error: /usr/lib/libKF5WidgetsAddons.so.5: undefined symbol: _ZNK19QAbstractTableModel7siblingEiiRK11QModelIndex


> > Can you test commenting `#define WORKAROUND_QT_TRAY_DBUS` in owncloudgui.cpp (2.0 branch) and check whether that makes a difference for the Qt 5.5.0 build/run case?

> This fixes the context menu

Yes, I can confirm that it fixes it for me too.

**Comment by ckamm** [comment]
Thanks @protist @nqn76 ! So the Fedora Qt 5.5.0 tray workaround breaks the context menu on arch...

Does the context menu actually work and update for you?
* Can you quit with 'Quit'?
* Does the menu change when you add a new account?

Because these were the bugs - plus crashes - we're seeing on Fedora 22 with Qt 5.5.0, KDE 5 and Plasma in #3672.

**Comment by protist** [comment]
> Can you quit with 'Quit'?

Yes.

> Does the menu change when you add a new account?

Yes.

Oddly, I see two Quit entries. At first, it looked like this:
![context menu](http://i.imgur.com/nhYWHFl.png)

And the second time it looked slightly different.
![context menu 2](http://i.imgur.com/WdbhmVD.png)

The "Quit" with the icon gives me an "Are you sure?" pop-up, and the other quit works instantly.

Finally, clicking the account names does nothing. I'm not sure if that is the expected behaviour.

**Comment by ckamm** [comment]
@protist @nqn76 It looks like the kde platform integration plugin could be to blame. Can you check what the tray looks like with `XDG_CURRENT_DESKTOP=xfce`?

**Comment by guruz** [comment]
@protist @nqn76 To clarify: you either need to ```export XDG_CURRENT_DESKTOP=xfce``` or you need to ```XDG_CURRENT_DESKTOP=xfce owncloud```

**Comment by ckamm** [comment]
@protist @nqn76 Which version of the `/usr/lib64/qt5/plugins/platformthemes/KDEPlatwormTheme.so` are you running? I guess it already contains the patch talked about here: https://bugzilla.redhat.com/show_bug.cgi?id=1255902 ?

**Comment by protist** [comment]
After running `XDG_CURRENT_DESKTOP=xfce owncloud`, the context menu works perfectly. I'm also only getting the one "Quit ownCloud" item, which quits immediately. I don't see the "Quit" entry with the icon.

> Which version of the `/usr/lib64/qt5/plugins/platformthemes/KDEPlatwormTheme.so` are you running?

This file does not exist in my system. In fact, there is no directory `/usr/lib64/qt5/plugins/platformthemes`, and no file called `KDEPlatwormTheme.so` on my system.

**Comment by nqn76** [comment]
Also WFM with XDG_CURRENT_DESKTOP=xfce. We have frameworkintegration 5.13 in Arch, unpatched.

**Comment by ckamm** [comment]
Thanks. So once the frameworkintegration crash bug in 5.12.0 is fixed, we still have the issue that the workaround for the Qt dbusmenu bug breaks the context menu with the KDE platform theme.

**Comment by ckamm** [comment]
@protist @nqn76 I'm waiting for the Fedora fix to go through so I can reproduce your issue. The change d91e312 should disable the workaround that breaks with the KDE platform theme. Could you apply the patch (it's not yet in the 2.0 branch) and test it?

Instructions:
```
# go to current state of 2.0 branch first...
git fetch https://github.com/ckamm/mirall.git d91e312d2478adfdd01d14d7412374b020a8adb8
git cherry-pick FETCH_HEAD
```
And then rebuild as usual.

**Comment by ckamm** [comment]
Prefer the more recent `f74b60b1ccc4d277c16eba9f7ddec0bbbdb42b61`

**Comment by protist** [comment]
I'm getting `error: no such remote ref f74b60b1ccc4d277c16eba9f7ddec0bbbdb42b61`. Do I need to specify the remote branch somehow, since it's not in `master`?
```
$ git clone https://github.com/owncloud/client.git
...
$ cd client
$ git checkout 2.0
Branch 2.0 set up to track remote branch 2.0 from origin.
Switched to a new branch '2.0'
$ git fetch https://github.com/ckamm/mirall.git f74b60b1ccc4d277c16eba9f7ddec0bbbdb42b61
error: no such remote ref f74b60b1ccc4d277c16eba9f7ddec0bbbdb42b61
```

**Comment by ckamm** [comment]
@protist It works for me. Maybe try fetching `b3706-workaround` instead?

**Comment by protist** [comment]
Yes, `git fetch https://github.com/ckamm/mirall.git b3706-workaround` worked.

And the context menu works fine again (although I still get the two quit items).

**Comment by ckamm** [comment]
@protist Nice, thanks for testing. The extra quit item is probably added by the KDE integration, we can't affect it.

**Comment by rperezb** [comment]
Following @protist comment (works) closing the issue
