### PR TITLE
Attempt to fix Jenkins

### PR DESCRIPTION
**Pull request by ogoffart**
Just to find out what's the problem on the CI

### CODE REVIEW

**Comment by ogoffart** [comment]
The error is

```
../libsync/libowncloudsync.so.2.4.0: undefined reference to `QKeychain::Job::setKey(QString const&)'
```

But /usr/lib/x86_64-linux-gnu/libqt5keychain.so contains

```
0000000000006f10 g    DF .text  000000000000000d  Base        QKeychain::WritePasswordJob::setKey(QString const&)
00000000000071b0 g    DF .text  000000000000000d  Base        QKeychain::DeletePasswordJob::setKey(QString const&)
0000000000006dd0 g    DF .text  000000000000000d  Base        QKeychain::ReadPasswordJob::setKey(QString const&)
```

Maybe the headers and the binary don't match.

**Comment by ogoffart** [comment]
The symbol was changed in the commit e6e828c33b09f84a954f9885d0b4efd706bcd439 in qtkeychain.

**Comment by ogoffart** [comment]
So I added -DCMAKE_PREFIX_PATH=/var/lib/jenkins/qt/5.6.2 in the Jenkins file so it picks the right Qt5Keychain,  otherwise it tries to link against the system qtkeychain which is too old.

I am not sure why the build worked with Qt 5.5's qtkeychain. Maybe because it was older and that it could still link with the system's qtkeychain without error.
