### ISSUE TITLE
Mirall 1.6 Qt5

### ISSUE THREAD

**Issue by nedimhx** [owncloud/client#1715]
Hello, I get this message when try to cmake 

CMake Error at cmake/modules/QtVersionAbstraction.cmake:26 (message):
  Qt 5 not found, but application depends on Qt5 on Windows and Mac OS X
Call Stack (most recent call first):
  CMakeLists.txt:34 (include)

-- Configuring incomplete, errors occurred!

How to install Qt5 ?

Regards

**Comment by mohamed--abdel-maksoud** [comment]
Hi,
I just wanted to share what worked on OpenSUSE 13.1, basically it is the packages @danimo described with a couple of changes:
```bash
zypper install mingw32-qt5keychain-devel \
mingw32-libqt5-qtxmlpatterns \
mingw32-cross-libqt5-qmake \
mingw32-libqt5-qtxmlpatterns-devel \
mingw32-libqt5-qtserialport-devel \
mingw32-libqt5-qmldevtools-devel \
mingw32-libqt5-qtactiveqt \
mingw32-cross-libqt5-qttools \
mingw32-libqt5-qtimageformats-devel \
mingw32-libqt5-qtbase \
mingw32-libqt5-qtmultimedia \
mingw32-libqt5-qtscript \
mingw32-libqt5-qttools \
mingw32-qt5keychain \
mingw32-libqt5-qtsvg-devel \
mingw32-libqt5-qtmultimedia-devel \
mingw32-libqt5-qmldevtools \
mingw32-libqt5-qtwebkit-devel \
mingw32-libqt5-qtsensors-devel \
mingw32-libqt5-qtbase-devel \
mingw32-libqt5-qtsvg \
mingw32-libqt5-qtwinextras-devel \
mingw32-libqt5-qtserialport \
mingw32-libqt5-qtimageformats \
mingw32-libqt5-qtquickcontrols \
mingw32-libqt5-qtdeclarative \
mingw32-libqt5-qtsensors \
mingw32-libqt5-qttranslations \
mingw32-libqt5-qtwinextras \
mingw32-angleproject-devel
```
I hope this helps.

**Comment by OoTBDS** [comment]
@mikeazo I'm getting the following: (It looks like you got this sorted before)
[ 89%] Linking CXX executable ../../bin/owncloud.app/Contents/MacOS/owncloud
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/owncloud.app/Contents/MacOS/owncloud] Error 1
make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
make: *** [all] Error 2

I'm running OSX 10.9, would appreciate the help!

**Comment by panjinming** [comment]
I have the same issue :"_main", referenced from:
implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/owncloud.app/Contents/MacOS/owncloud] Error 1
make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
make: *** [all] Error 2

I run in mac 10.12
Can you help me ?
