### ISSUE TITLE
Nemo integration

### ISSUE THREAD

**Issue by PascalAnimateur** [owncloud/client#2570]
For all LinuxMint users, Nemo integration is as simple as search & replacing "Nautilus" for "Nemo" (case sensitivity is important) in syncstate.py.
Get the file from pastebin here : http://pastebin.com/8CXV4q2t
Instructions for the lazy:
sudo wget http://goo.gl/TtfQeZ -O /usr/share/nemo-python/extensions/syncstate.py

**Comment by artem-sidorenko** [comment]
I tried it with latest version from master, sharing works as well

**Comment by NicolasGoeddel** [comment]
The script works very well. It would be nice if the overlay icons would be a little bit bigger, but that is not the problem of the script.

**Comment by nazar-pc** [comment]
Would be good to see this in Ubuntu repo in addition to nautilus, I'm using nemo from webupd8's ppa

**Comment by danimo** [comment]
@nazar-pc We cannot let our packages depend on random PPAs.

**Comment by artem-sidorenko** [comment]
@danimo could it be a possible way to go with seveal different packages for integration with Nemo/Caja/Nautilus like dropbox integration is done? http://packages.linuxmint.com/search.php?keyword=dropbox&release=any&section=any

**Comment by nazar-pc** [comment]
@danimo, and you should not. Packages there are the same as in Mint repository, just depend on `nemo` and `python-nemo` if you need it.

**Comment by danimo** [comment]
@nazar-pc Mint is not a valid targt in OBS. Only Ubuntu. And Ubuntu lacks he nemo-python package.

**Comment by nazar-pc** [comment]
Well, even if Mint will be added as target I'll not be able to use it because I have Ubuntu. While choosing between not supporting nemo at all, or support only those running Mint or who have ppa added, I'd choose latter.
BTW, it might be a good idea to push somehow `pyton-nemo` alongside with other plugins

**Comment by dragotin** [comment]
@nazar-pc I fail to understand. You say you have Ubuntu, but use Nemo on that?

**Comment by danimo** [comment]
Here is what I understand:

* Ubuntu has limited packages for nemo, i.e. lacks the `nemo-python` package, which can be obtained from the `webupd8/nemo` PPA.
* Mint has both the `nemo` and the `nemo-python` package

The problems:

* On Ubuntu, we could probably provide the package via a "Requires" line, but I don't think that's a good idea without official support from Ubuntu/Canonical (the PPA is not guranteed to stay around, and it's confusing for people that see unsatisfied dependencies).
* For Mint, we cannot provide packages because it hasn't been imported into OBS.

**Comment by nazar-pc** [comment]
Yes, I'm on Ubuntu and use Nemo because Nautilus lost many important features in last versions and still going towards simplification by loosing features.

I do not see any problem with providing nemo support on Ubuntu - you have no specific dev dependencies that will cause package fail to build, also it doesn't have to be installed automaticaly with owncloud-client. It can be just one more package in repository. For those who are using stock Nemo we may leave message in FAQ, that it might now work with stock Ubuntu's package.

**Comment by dragotin** [comment]
@nazar-pc true, there could be an additional package. Do you think you could provide a patch for the packages we have in https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client ?

**Comment by nazar-pc** [comment]
Unfortunately no, I'm not familiar with how to do that.

**Comment by NicolasGoeddel** [comment]
How can I add a submenu for the context menu in nemo like that from dropbox? I want to be able to copy a public link of a file to the clipboard without using the webinterface.

**Comment by abelass** [comment]
Hi,
With Linux Mint 17 32-bit and nemo 2.2.4 using owncloud client 1.8. 

After installing the script @PascalAnimateur nemo integration still doesn't seem to work

Did I miss something?

**Comment by danger89** [comment]
See: https://github.com/spinda/nemo-owncloud

**Comment by abelass** [comment]
Sorry, forgot tu update.  It was a python issue that is resolved now.

**Comment by danger89** [comment]
I noticed I needed to install the latest ownclient-client in order to let it work. Linux Mint is still using owncloud-client v1.6 if I remember correctly, the latest version is 1.8.

**Comment by RealRancor** [comment]
According to https://github.com/owncloud/client/pull/4260 Nemo support is included in the upcoming 2.1.1

**Comment by danimo** [comment]
yes, we should be able to close this, right @dragotin?

**Comment by dragotin** [comment]
We could if we had one other Nemo user that confirms that it works with a recent 2.1.1 build. @nickvergessen maybe?

**Comment by artem-sidorenko** [comment]
@dragotin @danimo 

I installed owncloud-client and owncloud-client-nemo from testing:

```
$ nemo
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/syncstate.py", line 23, in <module>
    from gi.repository import GObject, Nautilus
ImportError: cannot import name Nautilus
Initializing folder-color-switcher extension...
```

It works if I do 's/Nautilus/Nemo/g' in `/usr/share/nemo-python/extensions/syncstate.py`

**Comment by dragotin** [comment]
Yes, but that was fixed by 5ae81aa96cea1e4ef77a8f1b4b7b9eb99bde73ed . Please check the upcoming RC2.

**Comment by nickvergessen** [comment]
Tested `2.1.1~rc2-1.1` from our packaging, the file still contains `autilus` instead of `emo` and therefor does not work.
But it is copied into the correct nemo location (`/usr/share/nemo-python/extensions/syncstate.py`)

**Comment by nickvergessen** [comment]
@dragotin Had a look at the commit and found out: for me the `sed` is in `/bin/sed` not `/usr/bin/sed`
Maybe it's also the case on our package creation machine.

Can't we just use `sed` ?

**Comment by dragotin** [comment]
awesome @nickvergessen that is probably the reason. Thanks! I will change that to just use sed.

**Comment by dragotin** [comment]
@nickvergessen now its fixed. A nightly build is currently building in https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client which has that issue fixed. Thanks!

**Comment by nickvergessen** [comment]
Confirmed, I removed my fixed version before todays update.
Then updated to `2.1.1-1.1` and now the file is in the right place and has Nemo all over it.
Overlay icons show up and the share option is there as well: :+1: :white_check_mark: 

Mission successfully completed, closing
